// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"yuki-kabe/internal/data"
)

// Injectors from wire.go:

func initApp() (App, error) {
	dataData, err := data.NewData()
	if err != nil {
		return App{}, err
	}
	app := newApp(dataData)
	return app, nil
}
